# ==========================================================
# AUTOMATICALLY GENERATED BY CLOCKWORK INVARIANT GENERATOR
# ==========================================================
import math
import functools

# Active Invariants Registry
ACTIVE_INVARIANTS = []

def register_invariant(func):
    """Registers a callable invariant function into the active suite."""
    if callable(func) and func not in ACTIVE_INVARIANTS:
        ACTIVE_INVARIANTS.append(func)
    return func

def recognize_meaning(expression, invariants=None) -> bool:
    """Inferred from: M(e) = Recognize(e | Invariants) ⇔ Coherent(e)"""
    invariants_to_check = invariants if invariants is not None else ACTIVE_INVARIANTS
    for invariant in invariants_to_check:
        if callable(invariant) and not invariant(expression):
            return False
    return True

def invariant_guard(invariants=None):
    """Decorator that intercepts state updates and verifies coherence before returning."""
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            result = func(*args, **kwargs)
            # Evaluate returned expression against active invariants
            target_invariants = invariants if invariants is not None else ACTIVE_INVARIANTS
            if not recognize_meaning(result, target_invariants):
                raise ValueError(
                    f"[INVARIANT_VIOLATION] State update from '{func.__name__}' "
                    f"failed invariant checks: {result}"
                )
            return result
        return wrapper
    return decorator

@register_invariant
def default_coherence_check(state) -> bool:
    """Basic structural check ensuring numerical outputs remain bounded."""
    if isinstance(state, dict):
        x, y = state.get('x', 0.0), state.get('y', 0.0)
        # Ensure coordinates lie within unit manifold boundary
        return (x**2 + y**2) <= 1.05
    return True
